name: Format
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: jsonv2
    steps:
      - uses: actions/checkout@v4
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "1.25"
      - run: go test --race ./...
